travis-ci/travis-scheduler

lib/travis/scheduler/models/repository.rb, spec/travis/scheduler/models/repository_spec.rb
Resolves https://github.com/travis-ci/travis-ci/issues/4384
It's been tested in staging: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/435416#L66
=> Switch repository's scheme to https

.gitignore, .librato.yml, Gemfile, Gemfile.lock, lib/travis/scheduler.rb, lib/travis/scheduler/config.rb, lib/travis/scheduler/models/request.rb, lib/travis/scheduler/schedule.rb, lib/travis/scheduler/services/limit/configurable.rb, spec/spec_helper.rb, spec/support/active_record.rb, spec/travis/scheduler/models/repository_spec.rb, var/librato/scheduler/00_chart_scheduler_enqueued_total.json, var/librato/scheduler/01_chart_scheduler_median.json, var/librato/scheduler/02_chart_scheduler_95th_percentile.json, var/librato/scheduler/03_chart_scheduler_load_avg.json, var/librato/scheduler/04_chart_scheduler_memory_total.json, var/librato/scheduler/05_chart_postgres_load_avg.json
Bump travis-config to 1.0.0.rc1
Don't merge, yet.
=> Bump travis config

Gemfile, Gemfile.lock, lib/travis/scheduler/helpers/deep_dup.rb, lib/travis/scheduler/models/job/config.rb, spec/travis/scheduler/helpers/deep_dup_spec.rb, spec/travis/scheduler/services/limit/configurable_spec.rb
Going back to the ActiveRecord version 3.2 from 4.2.6 because of performance reasons
=> Sf ar bump config version 2

lib/travis/scheduler/payloads/worker.rb, spec/travis/scheduler/payloads/worker_spec.rb
This should fix the issue with travis-ci/travis-build#697
=> add event_type as payload

lib/travis/scheduler/models/job/config/normalize.rb, spec/travis/scheduler/models/job_config_spec.rb
Fixes https://github.com/travis-ci/travis-ci/issues/5669
=> Whitelist hostname addon

lib/travis/scheduler/models/job/config/normalize.rb, spec/travis/scheduler/models/job_config_spec.rb
To correspond to https://github.com/travis-ci/travis-build/pull/676.
=> Allow rethinkdb in PRs

lib/travis/scheduler/models/job/config/normalize.rb
This is required for https://github.com/travis-ci/travis-build/pull/356.
=> Allow jwt addon on PRs

Gemfile, Gemfile.lock, lib/travis/scheduler/services/enqueue_jobs.rb
Re https://github.com/travis-pro/team-teal/issues/1350
=> Ignore rollout owners for Scheduler 2.0 rollout

lib/travis/scheduler/payloads/worker.rb, spec/travis/scheduler/payloads/worker_spec.rb
So that travis-build can consume it
=> Add default_branch to worker payload

lib/travis/scheduler/models/request.rb, lib/travis/scheduler/payloads/worker.rb, spec/travis/scheduler/payloads/worker_spec.rb
=> Put PR head data onto payload

lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/job.rb, spec/travis/scheduler/serialize/worker_spec.rb
So that travis-build may consume it to set `$TRAVIS_ALLOW_FAILURE`
=> Add allow_failure to job payload

Gemfile.lock
This PR updates travis-config to get AMQPS support.
Related ticket: https://github.com/travis-pro/travis-enterprise/issues/171
=> update travis-config to get ampqps ssl fix

lib/travis/scheduler/record/organization.rb, lib/travis/scheduler/record/user.rb
fixing subscription retrieval inconsistencies and making a change for existing subscribers who sign up through marketplace
=> fixing subscription retrieval inconsistencies

lib/travis/queue/matcher.rb, lib/travis/queue/sudo.rb, spec/travis/queue_spec.rb
=> Add sudo override when Chrome use detected

Gemfile, Gemfile.lock
refs travis-ci/travis-gatekeeper#264
=> hdrhistogram: upgrade metriks deps to get more accurate percentiles

Gemfile, Gemfile.lock, lib/travis/marginalia.rb, lib/travis/scheduler.rb, lib/travis/scheduler/support/sidekiq.rb, lib/travis/scheduler/support/sidekiq/marginalia.rb, lib/travis/scheduler/worker.rb
=> query-comments: marginalia for postgres query comments

lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/job.rb, spec/travis/scheduler/serialize/worker_spec.rb
=> pass stage name to worker

lib/travis/queue/force_linux_sudo_required.rb, lib/travis/queue/sudo.rb, spec/spec_helper.rb, spec/support/queues.rb, spec/travis/queue/force_linux_sudo_required_spec.rb, spec/travis/queue_spec.rb
which is an owner-level feature.
=> Add queue sudo check for linux_sudo_required

lib/travis/queue/sudo.rb
placing sudo detection above specified value
=> Revert to previous sudo value precedence

lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/job.rb
refs travis-ci/reliability#152
=> control buildsh tracing via travis-rollout

.travis.yml
with explicit language and routing to single linux infrastructure
=> Ensure travis config is up to date

lib/travis/scheduler/record/job.rb, lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/job.rb, spec/travis/scheduler/serialize/worker_spec.rb
This lets travis-build expose TRAVIS_JOB_NAME.
=> Add name to job payload

lib/travis/scheduler/record/ssl_key.rb
To correspond to https://github.com/travis-ci/travis-api/pull/991.
=> Use OpenSSL::PKey::RSA::PKCS1_OAEP_PADDING when encrypting

.travis.yml
Objective:
- fix psql error in docker build
=> fix psql error in docker

lib/travis/scheduler/config.rb
Objective:
- host for build web url
=> host added for build web url

lib/travis/scheduler/record/job.rb, spec/travis/scheduler/record/job_spec.rb
This PR covers ordering of queueable jobs based on priority set at gatekeeper level
=> Order queueable jobs by priority

lib/travis/scheduler/billing/client.rb, lib/travis/scheduler/record/organization.rb, lib/travis/scheduler/record/user.rb, lib/travis/scheduler/serialize/worker/repo.rb, spec/travis/scheduler/record/organization_spec.rb, spec/travis/scheduler/record/user_spec.rb, spec/travis/scheduler/serialize/worker/repo_spec.rb, spec/travis/scheduler/service/enqueue_owners_spec.rb, spec/travis/scheduler/service/event_spec.rb, spec/travis/scheduler/service/notify_spec.rb
=> Default timeout fix

lib/travis/scheduler/record/organization.rb, lib/travis/scheduler/record/user.rb, spec/travis/queue_spec.rb, spec/travis/scheduler/record/organization_spec.rb, spec/travis/scheduler/record/user_spec.rb
Build for the paying customers should goto paid queues
=> Fix build queue

lib/travis/queue/matcher.rb, lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/job.rb, spec/travis/queue_spec.rb, spec/travis/scheduler/serialize/worker_spec.rb
=> added vm_size queue property

lib/travis/queue/matcher.rb, spec/travis/queue_spec.rb
improved queue matches for the private job and arch: ppc64le
=> improved queue matches for arch: ppc64le

lib/travis/scheduler/record/organization.rb, lib/travis/scheduler/record/user.rb
=> Epic maintenance prd 1

lib/travis/queue/matcher.rb, spec/travis/queue_spec.rb
Allow different queues to be used for private/public jobs
=> Allow different queues to be used for private/public jobs

lib/travis/scheduler/serialize/worker/job.rb
Fix for BSFY-183
Reopened https://github.com/travis-ci/travis-scheduler/pull/281
=> Fix for BSFY-183

lib/travis/scheduler/serialize/worker/job.rb
[SUPP-665](https://travisci.assembla.com/spaces/Support-bugs/tickets/realtime_list?ticket=665)
=> Using proper key for forked secrets

lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/request.rb, spec/travis/scheduler/serialize/worker_spec.rb
https://github.com/travis-ci/travis-scheduler/pull/305
* Add pull request draft data
* Add spec
* Update spec
* Fix
=> Release 240528

lib/travis/scheduler/serialize/worker.rb
Ticket: [TBT-3](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=3), PR: https://github.com/travis-ci/travis-scheduler/pull/308
=> Release 2024 07 08

lib/travis/scheduler/serialize/worker.rb, lib/travis/scheduler/serialize/worker/job.rb, spec/travis/scheduler/serialize/worker/job_spec.rb, spec/travis/scheduler/serialize/worker_spec.rb
Ticket: [TBT-39](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=39), PR: https://github.com/travis-ci/travis-scheduler/pull/309
=> Release 2024 07 10

lib/travis/scheduler/serialize/worker/ssh_key.rb, spec/travis/scheduler/serialize/worker/ssh_key_spec.rb
[TBT-3] Handle nil repo key (#316)
=> Release 2024 08 19

lib/travis/scheduler/jobs/limit/stages.rb, lib/travis/scheduler/model/stages.rb, lib/travis/scheduler/record/build.rb, lib/travis/scheduler/record/job.rb
[TBT-53](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=53) [Build Stages] Jobs cancellation doesn't work as expected (#317)
=> Release 2028 08 28

lib/travis/service.rb
[PDTQ-174](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/realtime_cardwall?ticket=174) - Redis is getting stuck with errors from sidekiq (worker)(#320)
=> Release 2024 10 16

lib/travis/scheduler/jobs/capacity/plan.rb, lib/travis/scheduler/record/organization.rb, lib/travis/scheduler/record/user.rb, spec/travis/scheduler/record/organization_spec.rb, spec/travis/scheduler/record/user_spec.rb, spec/travis/scheduler/serialize/worker/repo_spec.rb
[TBT-247](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=323) - trial timeout
=> Release 25 01 02

lib/travis/scheduler/serialize/worker/job.rb, spec/travis/scheduler/serialize/worker/job_spec.rb, spec/travis/scheduler/serialize/worker_spec.rb
[Tbt-325] send only correct and non-repeating env vars (#330)
=> Release 2025 04 14
