travis-ci/travis-scheduler

- lib/travis/scheduler.rb
- lib/travis/scheduler/services/limit/configurable.rb
- lib/travis/scheduler/services/limit/default.rb
- spec/travis/scheduler/services/limit/configurable_spec.rb
- spec/travis/scheduler/services/limit/default_spec.rb
If threre's a Redis key `scheduler.owner.limit.[owner_login]` set to a value > 0, then this will take precedence over all other limits/values (so it should not be set to a value lower than the limit currently paid for via the subscription).
E.g. if a customer is on a 2-builds plan, and you want to give them 5 extra, then set it to 7.
> Allow owner.limit to be set via redis (aka "boosts")

- .travis.yml
- README.md
- lib/travis/scheduler/config.rb
- lib/travis/scheduler/payloads/worker.rb
- lib/travis/scheduler/schedule.rb
- lib/travis/scheduler/support/features.rb
- lib/travis/scheduler/support/redis_pool.rb
- spec/spec_helper.rb
- spec/support/active_record.rb
- spec/support/stubs.rb
- spec/travis/scheduler/helpers/live_spec.rb
- spec/travis/scheduler/payloads/worker_spec.rb
- spec/travis/scheduler/services/enqueue_jobs_spec.rb
- spec/travis/scheduler/services/limit/configurable_spec.rb
- spec/travis/scheduler/services/limit/default_spec.rb
This adds a new key `vm_type` to the root of the worker payload, which
* defaults to "default" and
* will be "premium" if the feature flag `premium_vms` is set for either
the repository or its owner
This also duplicates the classes `Features` and `RedisPool` for the time
being and cleans up a few things about test setup and stub namings.
Implements travis-pro/team-blue#327
> Add `vm_type` to the worker payload

- Gemfile
- Gemfile.lock
- Rakefile
- config/database.yml
- spec/spec_helper.rb
- spec/support/db/create.sql
This change adds `travis-migrations` gem in order to access the most current DB `structure.sql` from which to migrate a test DB. 
It has been tested on travis-ci and the DB is successfully created/migrated, and all tests are passing.
> Use `structure.sql` from `travis-migrations` to create test DB

- lib/travis/scheduler/models/job.rb
- lib/travis/scheduler/payloads/worker.rb
- spec/support/stubs.rb
- spec/travis/scheduler/payloads/worker_spec.rb
https://github.com/travis-ci/travis-migrations/pull/7 adds
debug_otions to Jobs table, and we want to put it on the payload
so that travis-build can see it.
> Add job.debug_otions to payload

- lib/travis/scheduler/config.rb
- lib/travis/scheduler/payloads/worker.rb
- spec/travis/scheduler/payloads/worker_spec.rb
`cache_settings` will be the preferred cache configuration to be used by `travis-build`. This allows the cache configuration to be modified without altering the worker configurations, which is often an invasive change.
> Add `cache_settings` to the scheduler payload

- lib/travis/scheduler/config.rb
- lib/travis/scheduler/services/enqueue_jobs.rb
- spec/travis/scheduler/services/enqueue_jobs_spec.rb
I'm not quite sure how best to test this, or if this is even the best approach, but this should help us in moving jobs from one queue to another as we move between infrastructures.
> enqueue_jobs: Add the option to redirect from one queue to another

- Gemfile
- Gemfile.lock
- lib/travis/scheduler/branch_validator.rb
- lib/travis/scheduler/config.rb
- lib/travis/scheduler/encrypted_column.rb
- lib/travis/scheduler/github.rb
- lib/travis/scheduler/models/branch.rb
- lib/travis/scheduler/models/permission.rb
- lib/travis/scheduler/models/repository.rb
- lib/travis/scheduler/models/request.rb
- lib/travis/scheduler/models/user.rb
- lib/travis/scheduler/payloads/worker.rb
- lib/travis/scheduler/schedule.rb
- spec/travis/scheduler/branch_validator_spec.rb
- spec/travis/scheduler/models/request_spec.rb
- spec/travis/scheduler/payloads/worker_spec.rb
Due to a security incident we've forked the open travis-ci/travis-scheduler
to the closed travis-pro/travis-scheduler and started using that one for development.
Since the incident is now published we can move back to the old (open) repository.
> Merge changes made in travis-pro/master to travis-ci/master

- lib/travis/scheduler/models/job/config/normalize.rb
To correspond to https://github.com/travis-ci/travis-build/pull/702.
> Allow Browserstack addon in PR builds

- lib/travis/scheduler/schedule.rb
- lib/travis/scheduler/services/enqueue_jobs.rb
currently we create a new thread pool every time a schedule is run, this makes sure we only setup up one for the entire process
> setup one thread pool and pass it around

- lib/travis/scheduler/models/job/config/normalize.rb
- spec/travis/scheduler/models/job_config_spec.rb
This commit addresses the following problem:
This .travis.yml
```
env:
global:
- FOO=BAR
matrix:
-
matrix:
include:
- rvm: 2.3.0
gemfile: gemfiles/Gemfile.sinatra-edge
```
results in config
{:env=>[nil], :global_env=> ["FOO=BAR"]}
when it comes down to travis-scheduler.
Hitherto, we yielded
config[:env] = [{}, "FOO=BAR"]
which leads to problematic travis-build:
An error occurred while compiling the build script: undefined method `start_with?' for {}:Hash
See https://travis-ci.org/BanzaiMan/travis_production_test/jobs/148201050
> Suppress `[nil]` when it bubbles up in config

- lib/travis/scheduler/serialize/worker/config.rb
- lib/travis/scheduler/serialize/worker/config/addons.rb
- lib/travis/scheduler/serialize/worker/config/normalize.rb
- spec/travis/scheduler/serialize/worker/config_spec.rb
This is basically a port of
https://github.com/travis-ci/travis-scheduler/pull/34 to scheduler-2.
See that PR for rationale.
> Keep unencrypted addon config for jwt-aware addons if jwt is present

- lib/travis/scheduler/config.rb
- lib/travis/scheduler/helper/memoize.rb
- lib/travis/scheduler/limit/by_owner.rb
- lib/travis/scheduler/model/trial.rb
- spec/travis/scheduler/helper/memoize_spec.rb
- spec/travis/scheduler/limit_spec.rb
We currently use the same default config value for both trial and educational accounts. This allows setting a separate limit for trial builds.
> Limit by trial

- lib/travis/scheduler/serialize/worker/config/addons.rb
In this case, addon runs without sensitive data
> Allow sonarqube addon on external PRs

- lib/travis/scheduler/serialize/worker.rb
- lib/travis/scheduler/serialize/worker/request.rb
- spec/travis/scheduler/serialize/worker_spec.rb
We add the "full_name" of the repository which initiated the PR.
See https://developer.github.com/v3/pulls/#get-a-single-pull-request
for the structure of the PR data we receive from GitHub.
> Add PR slug name to payload

- lib/travis/scheduler/service/enqueue_owners.rb
In other words, enqueue jobs which are not allowed to fail first before those which are.
This is not perfect, as there are multiple threads enqueuing the jobs, but it should be good enough for a lot of cases.
> Deprioritize jobs which are allowed to fail

- lib/travis/scheduler/serialize/worker.rb
- spec/travis/scheduler/serialize/worker_spec.rb
This is a follow-up PR to https://github.com/travis-ci/travis-scheduler/pull/53, which put the token regardless of the setting.
> Put oauth_token only when config demands it

- lib/travis/queue/matcher.rb
- lib/travis/scheduler/limit/by_owner.rb
- lib/travis/scheduler/limit/by_queue.rb
- lib/travis/scheduler/limit/by_repo.rb
- lib/travis/scheduler/limit/jobs.rb
- lib/travis/scheduler/limit/state.rb
- lib/travis/scheduler/record/job.rb
- lib/travis/scheduler/service/enqueue_owners.rb
- spec/travis/scheduler/limit_spec.rb
- spec/travis/scheduler/service/notify_spec.rb
Triggered by severe queue time issues on support for larger orgs that have lots of OSX jobs clogging up even boosted concurrency.
Only accessible through an env var at the moment, as we haven't had any product discussion about this.
> Add a minimal by_queue limit

- lib/travis/scheduler/limit/jobs.rb
- lib/travis/scheduler/record/job.rb
this rolls back things from earlier today because queries where timing out on the join
> Cleanup rollout

- lib/travis/scheduler/limit/by_stage.rb
- spec/travis/scheduler/limit_spec.rb
Addresses https://github.com/travis-ci/travis-ci/issues/7776
Sorting jobs in the database means we sort strings alphabetically, i.e. `1.1 < 10.1 < 2.1` ... which is really not what we want.
> Fix ordering stages

- Gemfile.lock
GitHub introduced a number of new mergable states with the GHE 2.10.X series. We fixed this in .com (and with GitHub.com) but these fixes hadn't made it into Enterprise yet. This caused some problems with one of our customers using the protected branch feature to have issues with PRs triggering builds.
> [Enterprise 2.1] Upgrade GH gem to get new mergeable states

- lib/travis/scheduler/config.rb
- spec/travis/scheduler/config_spec.rb
This enables using https://github.com/travis-ci/travis-config/blob/master/spec/travis/config/env_spec.rb#L71-L83 for queues config.
One thing that currently does not work is using an array such as `services: ['docker']` for selection, because of a bug in travis-config (which should be trivial to fix).
> Support queue config via generic env vars

- lib/travis/scheduler/service/notify.rb
- spec/travis/scheduler/service/notify_spec.rb
This will allow us to switch to per-user channels instaed of
per-repo channels
> Send `user_ids` along with pusher message if user-channel enabled

- lib/travis/owners/group.rb
- lib/travis/scheduler/config.rb
- lib/travis/scheduler/limit/by_owner.rb
- lib/travis/scheduler/limit/by_public.rb
- lib/travis/scheduler/limit/jobs.rb
- lib/travis/scheduler/limit/state.rb
- lib/travis/scheduler/record/job.rb
- spec/travis/scheduler/limit_spec.rb
This is a pretty hack'ish solution to the problem, and we'd definitely want to get back to this with a refactoring.
Issues with the current implementation/design:
* `Limit::Jobs` implements an `AND` relation for all `Limit` strategies: https://github.com/travis-ci/travis-scheduler/blob/master/lib/travis/scheduler/limit/jobs.rb#L84
* `Limit::ByOwner` internally implements an `OR` relation (by the way of picking the first value it finds): https://github.com/travis-ci/travis-scheduler/blob/master/lib/travis/scheduler/limit/by_owner.rb#L30
... so the new logic has to go *into* `Limit::ByOwner`, which is designed/meant for having a single max value, and a single current value.
> First stab at a merged limit strategy

- .gitignore
- Gemfile.lock
- script/generate-job-payload.rb
The addition of `script/generate-job-payload.rb` permits retrieving the JSON representation of a given job:
```
$ heroku run -a travis-scheduler-staging script/generate-job-payload.rb 615732
Running script/generate-job-payload.rb 615732 on ⬢ travis-scheduler-staging... up, run.1626 (Hobby)
[...]
{"type":"test","vm_type":"default","queue":"builds.ec2","config":{"language":"ruby","sudo":false,"install":true,"script":["cat ~/build.sh"],"notifications":{"email":false,"slack":{"rooms":[{"secure":"woohoo/lallaa++fanko+blah/asefasf+mojitbit="}],"template":["Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration} (elapsed time: %{elapsed_time}) subject: %{commit_subject} message: …
```
> Add script/generate-job-payload.rb

- lib/travis/scheduler/limit/by_queue.rb
- spec/travis/scheduler/limit_spec.rb
```
BY_QUEUE_DEFAULT:             1
BY_QUEUE_NAME:                builds.ec2
I c19e6f Evaluating jobs for owner group: user svenfuchs
I c19e6f max jobs for user svenfuchs by default: 5
I c19e6f max jobs for user svenfuchs by queue builds.ec2: 1
I c19e6f user svenfuchs: total: 4, running: 0, queueable: 1
I c19e6f enqueueing job 628222 (svenfuchs/test-2)
I c19e6f Setting queue to builds.ec2 for job=628222
```
> Allow setting a global default for the by_queue limit

- lib/travis/scheduler/support/sidekiq.rb
From commit message:
```
Sidekiq Pro introduces algorithms to work more reliably than the regular
version. Till now we use the one called `reliable_fetch!`. It's
deprecated and it will be removed in next major version and
`super_fetch!` is now recommended way.
```
More info here: https://github.com/mperham/sidekiq/wiki/Reliability
> Use Sidekiq's super_fetch! method

- lib/travis/scheduler/serialize/live.rb
- lib/travis/scheduler/service/notify.rb
- spec/travis/scheduler/serialize/live_spec.rb
We will be treating the updated_at column as a record's version.
> Send `updated_at` for builds and jobs with Pusher

- lib/travis/owners/group.rb
- spec/travis/owners_spec.rb
since we're using the owner group's `key` for locking we need to make sure it's the same no matter the order
> sort logins for owner groups

- lib/travis/scheduler/record/request.rb
- spec/travis/scheduler/record/request_spec.rb
We shouldn't rely on the repo slug being the same
on head and pr, since repos are easily renamed.
https://github.com/travis-pro/team-teal/issues/2133
> Compare github ids when checking for non-repo forks

- lib/travis/queue/matcher.rb
- lib/travis/queue/sudo.rb
- spec/travis/queue_spec.rb
Reverts travis-ci/travis-scheduler#118
Due to config type errors in production.
https://sentry.io/travis-ci/org-scheduler-production/issues/431771133/
https://sentry.io/travis-ci/org-scheduler-production/issues/431651882/
Let's figure it out and reintroduce once production has stabilised.
> Revert "Add sudo override when Chrome use detected"

- lib/travis/scheduler/limit/jobs.rb
* scheduler.stats.queueable => scheduler.stats.enqueued (number of jobs enqueued in this scheduler run)
* remove scheduler.stats.total (it stands for "currently not running" which is not very useful)
* introduce scheduler.stats.concurrent to indicate current concurrency level (scheduler.stats.enqueued + scheduler.stats.running)
> honeycomb: change scheduler stats to be less confusing

- spec/spec_helper.rb
While discussing performance improvements for scheduler @igorwwwwwwwwwwwwwwwwwwww  and I thought this would be a useful addition to our tests.
Output looks like:
```
........................................................................
Number of SQL queries performed:
{
"": 4243,
"SCHEMA": 99,
"SQL": 2998,
"Request Load": 560,
"User Load": 597,
"Organization Load": 104,
"Job Load": 82,
"Repository Load": 450,
"Subscription Load": 180,
"Stage Load": 5
}
```
> Optionally display the number of SQL queries performed during test runs

- lib/travis/scheduler/limit/by_owner.rb
- lib/travis/scheduler/limit/jobs.rb
- spec/travis/scheduler/limit_spec.rb
This is the compromise we reached as part of https://github.com/travis-ci/reliability/issues/5, since counting by each limit type has a significant performance impact.
For now, we just want to count the jobs that are waiting for concurrency (although **not exclusively for concurrency**) and send this number to honeycomb.
Question:
Should this already pick up jobs waiting after The Merge? (it doesn't currently and I'm not sure if that's expected or not)
> Count jobs waiting for concurrency

- lib/travis/scheduler/service/enqueue_job.rb
- lib/travis/scheduler/service/notify.rb
In order to give more information to Team Jade that they could use to upsell clients, we should also keep track of how long jobs are waiting (based on the different limits that are imposed) to be scheduled and send that to Honeycomb. 
I initially calculated that as `Time.now` (which is the time when the job is actually sent to one of the infra queues to be run by the worker) - `Time.at(job['created_at'])`, but that meant getting huge durations for jobs that were restarted (which had `created_at` dates long in the past). Therefore, I think using `updated_at` should work well enough in this case.
> Track the time jobs spend waiting to be scheduled

- lib/travis/scheduler/record/organization.rb
- lib/travis/scheduler/record/user.rb
- spec/travis/scheduler/record/organization_spec.rb
- spec/travis/scheduler/record/user_spec.rb
- spec/travis/scheduler/serialize/worker/repo_spec.rb
Wanted to provide more context for the timeout knob, especially around the topic of adjusting it upwards, which @igorwwwwwwwwwwwwwwwwwwww pointed out to me can cause (and has caused) issues.
> Add additional context for configurable timeouts

- Procfile
- bin/sidekiq-pgbouncer
to add the buildpack to an application:
```
$ heroku buildpacks:add https://github.com/travis-ci/heroku-buildpack-pgbouncer -a travis-scheduler-staging
$ heroku config:set PGBOUNCER_DEFAULT_POOL_SIZE=5 PGBOUNCER_CONNECT_QUERY='set statement_timeout to 10000' -a travis-scheduler-staging
$ heroku config:set PGBOUNCER_ENABLED=true -a travis-scheduler-staging
```
and on prod (to match `SIDEKIQ_CONCURRENCY`):
```
$ heroku config:set DB_POOL=30 SIDEKIQ_CONCURRENCY=30 -a travis-scheduler-production
$ heroku config:set DB_POOL=25 -a travis-pro-scheduler-prod
```
refs travis-ci/reliability#97 https://github.com/travis-ci/travis-gatekeeper/pull/346
> pgbouncer buildpack for more effective connection pooling

- lib/travis/scheduler/record/organization.rb
- lib/travis/scheduler/record/user.rb
- spec/travis/scheduler/record/organization_spec.rb
- spec/travis/scheduler/record/user_spec.rb
If a User or Org is an "Educational" account, use the "subscribed timeout" value.
> Recognize educational users as subscribed for timeout purposes

- lib/travis/scheduler/record/job.rb
`read_attribute` returns `nil` anyway if the column is missing, but it looks like they are currently still debating if that is a bug or not https://github.com/rails/rails/issues/31017
> Protect against missing column config on requests, builds, jobs

- lib/travis/scheduler/serialize/worker.rb
- lib/travis/scheduler/serialize/worker/repo.rb
- spec/travis/scheduler/serialize/worker_spec.rb
This is intended to complement https://github.com/travis-ci/worker/pull/466
The implementation here reads config hashes from yaml config, which may be good enough for the beta period, but we may also want to eventually move to storing the config hashes in database or similar.
> Include vm config in job serialization if present

- lib/travis/scheduler/jobs/capacities.rb
- lib/travis/scheduler/jobs/capacity/boost.rb
- lib/travis/scheduler/jobs/capacity/config.rb
- lib/travis/scheduler/jobs/capacity/education.rb
- lib/travis/scheduler/jobs/capacity/plan.rb
- lib/travis/scheduler/jobs/capacity/public.rb
- lib/travis/scheduler/jobs/capacity/trial.rb
- lib/travis/scheduler/model/boost.rb
- spec/travis/scheduler/jobs_spec.rb
> do the "right thing" for public/free jobs … and for all other capacities (`boost config plan education trial`) pick the first one that is applicable, in this order, and only respect this one, and discard all other ones
> Refactor Scheduler::Jobs to disregard all except one capacity besides public

- lib/travis/owners/config.rb
- lib/travis/scheduler/jobs/capacities.rb
- lib/travis/scheduler/jobs/capacity/base.rb
- lib/travis/scheduler/jobs/limits.rb
- lib/travis/scheduler/jobs/reports/capacities.rb
- lib/travis/scheduler/jobs/select.rb
- spec/travis/scheduler/jobs_spec.rb
- spec/travis/scheduler/service/enqueue_owners_spec.rb
This is a small refactoring to do less work in setting up capacities. As we only use `public` and one other applicable capacity there's no point in initializing all of them.
Also adds an additional log line that announces applicable capacities no matter if there actually are jobs to be processed (in order to make log output more consistent/usable).
> Refactor capacities

- lib/travis/scheduler/serialize/worker/config/addons.rb
We want the Homebrew addon to be able to run for all builds including PRs from forks, so it should be on the list of safe addons.
This should fix https://github.com/travis-ci/travis-ci/issues/10149.
> Add homebrew to the list of safe addons

- .gitignore
- lib/travis/queue/force_linux_sudo_required.rb
- lib/travis/queue/sudo.rb
- lib/travis/scheduler/config.rb
- spec/travis/queue/force_linux_sudo_required_spec.rb
and change the feature checking to look at both owner and repo.
The way this is _supposed_ to work, based on how the similar code for setting `sudo: required` when `dist: precise` is for first-job repos and a random percentage of already-activated repos to be considered for having the feature _activated_.  Once activated, the repo will remain activated unless a Travis support human with access to admin tooling de-activates the feature.
> Prepare "linux_sudo_required" for percentage-based rollout

- lib/travis/scheduler/serialize/worker.rb
- lib/travis/scheduler/serialize/worker/job.rb
This allows us to have more control over the rollout progression of [warmer](https://github.com/travis-ci/warmer). We can enable it for a percentage of owners. Worker will check the `warmer` flag in the payload.
Code based on https://github.com/travis-ci/travis-scheduler/pull/165.
refs travis-ci/reliability#195
> warmer: control rollout via feature flag

- lib/travis/scheduler/serialize/worker/job.rb
This way we get a sample of all jobs and not the same jobs from the same owners. This also improves fault tolerance. If tracing causes an issue, users are at least able to restart the job without triggering the problem repeatedly.
This also removes the ability to set `trace: true` in `.travis.yml`. It's safer to manage that via rollout.
vaguely refs https://github.com/travis-ci/reliability/issues/195
> apply trace and warmer feature flags to random sample of jobs

- Gemfile
- Gemfile.lock
https://nvd.nist.gov/vuln/detail/CVE-2018-16471
> Bump rack version to  pick up security patches

- lib/travis/scheduler/jobs/limits.rb
This prevents the case where we filter out a bunch of jobs by repo or by queue, then go and reject some of the jobs we did select by build stage, leaving several jobs unconsidered.
> Apply build stages limit first

- lib/travis/scheduler/jobs/state.rb
- spec/travis/scheduler/jobs_spec.rb
From commits:
```
Don't include migrated jobs when calculating concurrency
When we migrate a build history it's possible that some jobs are still
running on .org. We shouldn't count them towards concurrency limits
because they're technically running on .org
```
```
Don't enqueue jobs that are migrated from .org
When we migrate build history some of the builds may be in the created
state. We don't want to enqueue them as then they would be running on
both platforms.
```
> Don't count migrated jobs towards concurrency limit and don't enqueue them

- lib/travis/scheduler/jobs/state.rb
- lib/travis/scheduler/limit/jobs.rb
- lib/travis/scheduler/limit/state.rb
- lib/travis/support/filter_migrated_jobs.rb
- spec/travis/scheduler/limit/com_spec.rb
I've already attempted it to fix the problem in 01139a4, but I only
fixed one code path, which is currently not used, so the changes didn't
go into effect. This commit applies the changes to the other code path
as well.
The reason we need to do it is because when we migrate jobs from .org to
.com they might still be in a state that is considered by gatekeeper. So
they might be started but they're running on .org not .com, thus we
shouldn't count them as running on .com. The same with new jobs - we
don't want to start them as they would start on .org anyway.
I decided to filter these jobs in code instead of in the database
because the number of jobs that we fetch from the database is relatively
small and if I had to do it in the DB I would have to always join jobs
with repositories, which …
> Don't count migrated jobs towards concurrency and don't enqueue them

- lib/travis/scheduler/serialize/worker/config/decrypt.rb
- lib/travis/scheduler/serialize/worker/config/normalize.rb
- spec/travis/scheduler/serialize/worker/config_spec.rb
the changes in the spec are formatting only, except for
```ruby
it { should eql env: ['FOO=foo', 'BAR=bar', 'SECURE BAZ=baz'], global_env: ['FOO=foo', 'BAR=bar', 'SECURE BAZ=baz'] }
```
which used to be
```ruby
it { should eql env: ['FOO=foo BAR=bar', 'SECURE BAZ=baz'], global_env: ['FOO=foo BAR=bar', 'SECURE BAZ=baz'] }
```
which should be alright.
> allow env vars to be hashes

- lib/travis/support/secure_config.rb
before: 
after:
(we might also change travis-build to actually output a message to the log if one of the env vars is `[unable to decrypt]`)
> more useful message when decryption failed

- Dockerfile
Objective:
- fix 
```
warning: pgbouncer buildpack not found, setting PGBOUNCER_ENABLED=false
port=3000 rack_env=production web_concurrency=4 nginx_workers=4
/usr/bin/env: 'ruby_executable_hooks': No such file or directory
```
> fix ruby executable hook error

- lib/travis/queue/matcher.rb
- lib/travis/scheduler/record/job.rb
This PR introduced 2 changes:
1. Allows to use `paid` flag in queue config. The flag is taken into account only if it exists in a config for certain queue.
2. Handles arrays for all fields.
> Separating queues 3.1

- .travis.yml
The workaround is no longer necessary after https://github.com/travis-ci/build-configs/pull/4
> Pull db-setup.yml from `master` branch

- lib/travis/scheduler/jobs/capacity/plan.rb
Cancel jobs that have been not queued for more than a day due to billing allowance.
billing-v2 terminator is not cancelling these jobs, as they have not been queued yet, which leaves them in "stuck" state.
> [BV2-168] Fix stuck jobs due to billing

- lib/travis/scheduler/service/set_queue.rb
- spec/travis/scheduler/service/event_spec.rb
When stoping jobs of a cancelled build from being queued we need to consider not all jobs have stages.
> Not all jobs have stages

- lib/travis/scheduler/service/set_queue.rb
Stop build from not getting queued if there is an exception
> Stop build from not getting queued

- .travis.yml
Restrict ruby gem-update to 3.4.22 because it still supports ruby 2.6
> Restrict ruby gem-update version
